### ISSUE TITLE
Lab-D instructions - additional steps request

### ISSUE THREAD

**Issue by lhardee-chase** [mafudge/ist346-content#3]
Question: would it be better adding the content to the lab instructions? The attached is my attempt to capture steps from the video. It seemed to work. and pretty sure you can clean it up  ... See attached.

[Lab-D Instructions from LinkedIn Video.docx](https://github.com/mafudge/ist346-content/files/6679326/Lab-D.Instructions.from.LinkedIn.Video.docx)

**Comment by mafudge** [comment]
Personally its good experience to learn how to follow commands from a video! I do it all the time!
