### ISSUE TITLE
Lab-G: yml file and instructions update

### ISSUE THREAD

**Issue by lhardee-chase** [mafudge/ist346-content#4]
Order of load balance sequence in compose.yml does not match the instructions. Per instructions, order should begin with “roundrobin”; however, default is “uri”  See below

screenshot of yml file
![image](https://user-images.githubusercontent.com/43323846/122615508-a0e41880-d056-11eb-83b9-9376061870c5.png)

screenshot of instructions
![image](https://user-images.githubusercontent.com/43323846/122615596-c4a75e80-d056-11eb-9b43-f8ccc05dea0e.png)

**Comment by mafudge** [comment]
fixed!
