### ISSUE TITLE
Lab-K Step 7: Instructions update needed

### ISSUE THREAD

**Issue by lhardee-chase** [mafudge/ist346-content#6]
Email does not send/received without complete header. Additional header info and new screenshot needed. See below.

Per instruction - 
5.	Now you can send an email, first define who the message is from:
mail from: me@mycompany.com
The response will say:
250 2.1.0 Ok
6.	Second define the recipient:
rcpt to: myuser@mycompany.com
Again you will see the response:
250 2.1.0 Ok
7.	Now set the data:
data
And you will see the message:
354 End data with <CR><LF>.<CR><LF>
8.	Then enter the following:
Subject: Test Email

My Test Email

**Please add ** ‘From’ and ‘Date’ header along with the ‘Subject’ Header to successfully send the email.” This worked and the email was received.

![image](https://user-images.githubusercontent.com/43323846/122616297-1d2b2b80-d058-11eb-8484-4e08fc7b9419.png)

**Comment by mafudge** [comment]
fixed
